@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RemoveSkillCommandParser" as RemoveSkillCommandParser LOGIC_COLOR
participant "r:RemoveSkillCommand" as RemoveSkillCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "personToEdit:Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute("removeSkill 1 Java")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("removeSkill 1 Java")
activate AddressBookParser

create RemoveSkillCommandParser
AddressBookParser -> RemoveSkillCommandParser
activate RemoveSkillCommandParser

RemoveSkillCommandParser --> AddressBookParser
deactivate RemoveSkillCommandParser

AddressBookParser -> RemoveSkillCommandParser : parse("1 Java")
activate RemoveSkillCommandParser

create RemoveSkillCommand
RemoveSkillCommandParser -> RemoveSkillCommand
activate RemoveSkillCommand

RemoveSkillCommand --> RemoveSkillCommandParser :
deactivate RemoveSkillCommand

RemoveSkillCommandParser --> AddressBookParser : r
deactivate RemoveSkillCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
RemoveSkillCommandParser -[hidden]-> AddressBookParser
destroy RemoveSkillCommandParser

AddressBookParser --> LogicManager : r
deactivate AddressBookParser

LogicManager -> RemoveSkillCommand : execute(m)
activate RemoveSkillCommand

RemoveSkillCommand -> Model : getFilteredPersonList()
activate Model

Model --> RemoveSkillCommand : lastShownList
deactivate Model

RemoveSkillCommand -> Person : removeSkill(skillToRemove)
activate Person

Person --> RemoveSkillCommand : editedPerson
deactivate Person

RemoveSkillCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model

Model --> RemoveSkillCommand
deactivate Model

create CommandResult
RemoveSkillCommand -> CommandResult
activate CommandResult

CommandResult --> RemoveSkillCommand
deactivate CommandResult

RemoveSkillCommand --> LogicManager : result
deactivate RemoveSkillCommand

[<--LogicManager
deactivate LogicManager
@enduml
